#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Check_Environment

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Disk space
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
    
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
        
    - name: Force Enable binfmt_misc in Kernel
      run: |
        echo "==========debug============"
        ls -l openwrt/
        echo "==========2nd=============="
        cat openwrt/Config.in
        echo "==========================="
        ls -l openwrt/target/linux/x86/
        echo "==========================="
        
        echo "CONFIG_EMBEDDED=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_IA32_EMULATION=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_X86_X32=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_X86_32=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_X86_32_COMPAT=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_COMPAT=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_X86_PAE" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_QEMU_EMULATOR" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_BINFMT_ELF_CORE=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_BINFMT_MISC=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_BINFMT_ELF=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_COMPAT_BINFMT_ELF=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_BINFMT_SCRIPT=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_X86_MSR=y" >> openwrt/target/linux/x86/config-6.6
        echo "CONFIG_EMBEDDED=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_IA32_EMULATION=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_X86_X32=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_X86_32=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_X86_32_COMPAT=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_COMPAT=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_X86_PAE" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_QEMU_EMULATOR" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_BINFMT_ELF_CORE=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_BINFMT_MISC=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_BINFMT_ELF=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_COMPAT_BINFMT_ELF=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_BINFMT_SCRIPT=y" >> openwrt/target/linux/x86/config-6.12
        echo "CONFIG_X86_MSR=y" >> openwrt/target/linux/x86/config-6.12

        echo "==========debug============"
        
        

    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
        echo "==========================="
        pwd
        ls -l
        echo "==========================="
        cat openwrt/.config | grep BINFMT
        echo "==========================="
        cat openwrt/config.buildinfo | grep BINFMT
        
